---
- name: Add the user "juri"
  user:
    name: juri

- name: Set juri's authorized key
  authorized_key:
    user: juri
    key: https://github.com/hudolejev.keys

- name: Add the user "roman"
  user:
    name: roman

- name: Set roman's authorized key
  authorized_key:
    user: roman
    key: https://github.com/romankuchin.keys

- name: Create user backup
  user:
    name: backup
    shell: /bin/bash
    home: /home/backup
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
