---
- name: Install keepalived
  apt:
    name: keepalived
    state: latest

- name: Configure keepalived
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
  notify: Restart keepalived

- name: Download keepalived exporter
  unarchive:
    src: https://github.com/cafebazaar/keepalived-exporter/releases/download/v1.1.0/keepalived-exporter-1.1.0.linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes

- name: Keepalived exporter service
  template:
    src: keepalived-prometheus-exporter.service.j2
    dest: /etc/systemd/system/keepalived-prometheus-exporter.service
  notify:
    - Reload systemd
    - Restart keepalived exporter