---
- name: Install required tools for Grafana installation
  apt:
    name: apt-transport-https
    update_cache: yes


- name: Add an apt key
  apt_key:
    url: https://packages.grafana.com/gpg.key


- name: Add Grafana repository
  apt_repository:
    filename: grafana
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Install Grafana
  apt:
    name: grafana
    update_cache: yes

- name: Reconfigure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart Grafana

- name: backup user to Grafana groups on VM1
  user:
    name: backup
    groups: grafana
    append: yes
