---
- name: Install uWSGI
  apt:
    name:
      - uwsgi
      - uwsgi-plugin-python3
    state: latest
    update_cache: yes

- name: Install PyMySQL for uWSGI
  apt:
    name: python3-pymysql
    state: latest
    update_cache: yes

- name: Add the uWSGI configuration
  template: 
    src: agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  notify: Restart uWSGI

- name: Check uWSGI (is started)
  service:
    name: uwsgi
    state: started
    enabled: yes
