{
 "title": "Dashboard-3",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "appname",
    "label": "Appname",
    "query": "SHOW TAG VALUES FROM syslog WITH KEY=appname"
   },
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES FROM syslog WITH KEY=hostname"
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": "SHOW TAG VALUES FROM syslog WITH KEY=severity"
   },
   { "name": "Query", "label": "Query" }
  ]
 },
 "panels": [
  { "title": "Systems' status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nginx Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nginx_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Bind Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Nginx requests",
   "type": "graph",
   "description": "Nginx requests per minute",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "VM1's DNS ",
   "type": "graph",
   "description": "DNS queries per minute for VM1",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"arniki-1:9119\"}[1m])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "VM2's DNS",
   "type": "graph",
   "description": "DNS queries per minute for VM2",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"arniki-2:9119\"}[1m])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "VM3's master DNS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total{instance=\"arniki-3:9119\"}[1m])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "VM1's CPU Load (%)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=\"arniki-1:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=\"arniki-1:9100\"}[1m])))) * 100) / count(count(node_cpu{instance=\"arniki-1:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "VM2's CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=\"arniki-2:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=\"arniki-2:9100\"}[1m])))) * 100) / count(count(node_cpu{instance=\"arniki-2:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "MySQL Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "MySQL ID",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL read-only Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "VM3's CPU (%)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu{instance=\"arniki-3:9100\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu{mode='idle',instance=\"arniki-3:9100\"}[1m])))) * 100) / count(count(node_cpu{instance=\"arniki-3:9100\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Memory Usage (%)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "(node_memory_MemTotal - node_memory_MemAvailable) / (node_memory_MemTotal) * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "MySQL q/min",
   "type": "graph",
   "description": "MySQL queries per minute",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[1m])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HAProxy Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "haproxy_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "HAProxy Server Status",
   "type": "stat",
   "description": "The information is acquired from two HAProxy instances, which contain information about each other. The result is a doubled amount of information. The solution is to request statistics only from a specific instance.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "haproxy_server_up{instance=\"arniki-1:9101\"}",
     "legendFormat": "{{ server }}"
    }
   ]
  },
  {
   "title": "Keepalived Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "keepalived_up", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Keepalived VRRP Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "Connection latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Connection latency (ms)",
   "type": "graph",
   "description": "Report of the connection latency from the 2nd VM to google.com, twitter.com and cloudflare.com",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "milliseconds" }
   ],
   "targets": [
    {
     "alias": "Target: [[tag_dst]]",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "dst" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "latency",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Syslog messages", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Syslog messages count",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Info",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "info" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    },
    {
     "alias": "Notice",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "notice" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    },
    {
     "alias": "Warning",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "warning" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    },
    {
     "alias": "Error",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "err" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    },
    {
     "alias": "Critical",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "crit" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    },
    {
     "alias": "Alert",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "alert" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    },
    {
     "alias": "Emergancy",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "severity", "operator": "=", "value": "emerg" },
      { "condition": "AND", "key": "hostname", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" }
     ]
    }
   ]
  },
  {
   "title": "Syslog messages",
   "type": "table",
   "description": "Report of syslog messages",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "appname" ], "type": "tag" }
     ],
     "measurement": "syslog",
     "select": [
      [
       { "params": [ "severity_code" ], "type": "field" }
      ],
      [
       { "params": [ "message" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "appname", "operator": "=~", "value": "/^$appname$/" },
      { "condition": "AND", "key": "severity", "operator": "=~", "value": "/^$severity$/" }
     ]
    }
   ]
  }
 ]
}